// <auto-generated />
namespace Mithuvai.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class oiop : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oiop));
        
        string IMigrationMetadata.Id
        {
            get { return "202408131856461_oiop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
